import { useEffect, useMemo, useState } from "react";
import { computeAccountEquitySnapshot } from "@/lib/portfolioMetrics";
import { useCapitalAdjustments, useSettings, useTrades } from "@/lib/store";
import {
  Activity,
  Crosshair,
  DollarSign,
  Info,
  PieChart,
  Settings as SettingsIcon,
  ShieldAlert,
  Trash2,
} from "lucide-react";
import CapitalSummary from "@/components/CapitalSummary";

const CLASSIFICATIONS = [
  { range: "85%+", label: "Near Matches", note: "Closest historical context. These trades carry the most statistical relevance." },
  { range: "70-84%", label: "Strong Matches", note: "Useful historical context with several matching conditions." },
  { range: "55-69%", label: "Loose Matches", note: "Included with low influence because similarity weighting reduces weak matches." },
  { range: "<55%", label: "Ignored", note: "Excluded from expected outcome calculations." },
];

const PIPELINE_STEPS = [
  "The app compares the new trade against closed journal trades only.",
  "Similarity uses setup, timeframe, BTC condition, alt condition, narrative strength, narrative category, and market cap tier.",
  "Each historical trade receives a 0-100% similarity value.",
  "Matches below 55% are ignored.",
  "Expected return and weighted win rate use similarity squared, so closer matches matter more.",
  "The historical snapshot is stored with the trade when it is journaled.",
];

const LAYERS = [
  { label: "Setup Type", weight: "30", note: "Breakout Retest, Double Bottom, Trend Continuation, Trendline Reclaim, or custom setup.", icon: PieChart },
  { label: "Timeframe", weight: "20", note: "Weekly, Daily, 4H, or 1H.", icon: Crosshair },
  { label: "BTC Condition", weight: "15", note: "Extreme Bullish through Extreme Bearish.", icon: Activity },
  { label: "Alt Condition", weight: "10", note: "Alt market context at trade entry.", icon: Activity },
  { label: "Narrative Strength", weight: "10", note: "Dead, Weak, Neutral, Active, or Hot.", icon: ShieldAlert },
  { label: "Narrative Category", weight: "5", note: "AI, DeFi, RWA, Infrastructure, Gaming, Meme, or Other.", icon: PieChart },
  { label: "Market Cap Tier", weight: "10", note: "Micro, Small, Mid, or Large Cap.", icon: Crosshair },
];

const DECISION_SCREEN = [
  { state: "Historical Matches", note: "How many similar closed trades exist in your journal." },
  { state: "Historical Performance", note: "Win rate, breakeven rate, loss rate, average return, best result, and worst result." },
  { state: "Expected Outcome", note: "Expected return and weighted historical win rate using similarity squared." },
  { state: "Confidence Level", note: "A simple label based on sample size and average similarity." },
];

const HARD_FILTERS = [
  { id: "N1", rule: "The app does not judge whether a trade should be taken.", result: "Neutral" },
  { id: "N2", rule: "TP and SL fields are used for planning and analytics, not similarity matching.", result: "Planning" },
  { id: "N3", rule: "Open trades are journal records but do not affect historical performance until closed.", result: "Analytics" },
];

const ALLOCATION_RULES = [
  { label: "Formula", value: "similarity squared", note: "A 95% match gets 0.9025 weight; a 70% match gets 0.49 weight." },
  { label: "Expected return", value: "weighted avg", note: "Historical returns are averaged using similarity weight." },
  { label: "Weighted win rate", value: "weighted avg", note: "Wins from closer matches count more than loose matches." },
  { label: "Snapshot", value: "frozen", note: "The output at entry time stays attached to the journal record." },
];

const GUARDRAILS = [
  "No verdict language is used.",
  "No allocation is generated by the app.",
  "Small samples should be treated as context, not certainty.",
  "Historical output changes as your journal grows; saved snapshots do not change.",
  "Average position size uses allocated dollars divided by the stored account capital snapshot when available.",
];

export default function Settings() {
  const { settings, updateSettings } = useSettings();
  const { trades } = useTrades();
  const { adjustments, addCapitalAdjustment, deleteCapitalAdjustment } = useCapitalAdjustments();
  const [capital, setCapital] = useState("");
  const [adjustAmount, setAdjustAmount] = useState("");
  const [adjustNote, setAdjustNote] = useState("");
  const [saved, setSaved] = useState(false);

  const equity = useMemo(() => {
    const closed = trades.filter((t) => t.outcome && t.actualPnlPct != null);
    return computeAccountEquitySnapshot(settings.totalCapital, closed, adjustments);
  }, [settings.totalCapital, trades, adjustments]);

  useEffect(() => {
    setCapital(String(equity.baseEquityUsd));
  }, [equity.baseEquityUsd]);

  const handleSave = () => {
    const baseUsd = parseFloat(capital);
    if (!isNaN(baseUsd) && baseUsd > 0) {
      updateSettings({ totalCapital: baseUsd });
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    }
  };

  const handleAdjustment = (adjustmentType: "add" | "withdraw") => {
    const amountUsd = parseFloat(adjustAmount);
    if (!Number.isFinite(amountUsd) || amountUsd <= 0) return;
    void addCapitalAdjustment({ adjustmentType, amountUsd, note: adjustNote || undefined }).then(() => {
      setAdjustAmount("");
      setAdjustNote("");
    });
  };

  return (
    <div className="p-6 space-y-8 pb-12">
      <div className="flex items-center justify-between border-b border-border pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-muted rounded-md">
            <SettingsIcon className="w-5 h-5 text-foreground" />
          </div>
          <div>
            <h1 className="text-base font-semibold">Settings & Reference</h1>
            <p className="text-xs text-muted-foreground mt-0.5">Configure capital and review the historical similarity model</p>
          </div>
        </div>
        <CapitalSummary />
      </div>

      <div className="border border-border/60 rounded-xl bg-card/20 p-4 shadow-sm relative overflow-hidden w-full">
        <div className="absolute top-0 left-0 w-1 h-full bg-foreground/20" />

        <div className="pl-2 space-y-4 w-full min-w-0">
          <div className="flex flex-col xl:flex-row xl:items-end gap-3 w-full">
            <div className="shrink-0 w-full sm:w-40">
              <div className="text-xs font-semibold mb-1.5">Base Account Capital</div>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                  <DollarSign className="w-3.5 h-3.5 text-muted-foreground" />
                </div>
                <input
                  type="number"
                  min="1"
                  step="100"
                  className="w-full bg-background border border-border rounded-md pl-8 pr-2 py-2 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
                  value={capital}
                  onChange={(e) => setCapital(e.target.value)}
                />
              </div>
            </div>

            <div className="flex-1 min-w-0 space-y-1.5">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Capital adjustments
              </div>
              <div className="flex flex-col sm:flex-row gap-2 w-full">
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  className="sm:w-28 shrink-0 bg-background border border-border rounded-md px-2.5 py-2 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
                  placeholder="Amount"
                  value={adjustAmount}
                  onChange={(e) => setAdjustAmount(e.target.value)}
                />
                <input
                  className="flex-1 min-w-0 bg-background border border-border rounded-md px-2.5 py-2 text-sm font-mono text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
                  placeholder="Note (optional)"
                  value={adjustNote}
                  onChange={(e) => setAdjustNote(e.target.value)}
                />
                <button
                  type="button"
                  className="shrink-0 px-3 py-2 text-xs font-mono bg-foreground text-background rounded-md hover:opacity-90 whitespace-nowrap"
                  onClick={() => handleAdjustment("add")}
                >
                  Add
                </button>
                <button
                  type="button"
                  className="shrink-0 px-3 py-2 text-xs font-mono border border-border rounded-md text-muted-foreground hover:text-foreground whitespace-nowrap"
                  onClick={() => handleAdjustment("withdraw")}
                >
                  Withdraw
                </button>
              </div>
            </div>
          </div>

          <div className="text-[11px] text-muted-foreground leading-relaxed flex items-start gap-2">
            <Info className="w-3.5 h-3.5 shrink-0 mt-0.5 opacity-70" />
            <span>
              Base equity drives account return and sizing hints. Deposits and withdrawals update net capital.
              Trading P&L is tracked separately and flows into net capital when trades close.
            </span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
            <div className="border border-border rounded-sm px-2.5 py-2">
              <div className="text-[10px] uppercase text-muted-foreground mb-0.5">Net capital</div>
              <div className="text-foreground">${equity.netEquityUsd.toLocaleString()}</div>
            </div>
            <div className="border border-border rounded-sm px-2.5 py-2">
              <div className="text-[10px] uppercase text-muted-foreground mb-0.5">Trading P&L</div>
              <div className={equity.tradingPnlUsd >= 0 ? "text-green-400" : "text-red-400"}>
                {equity.tradingPnlUsd >= 0 ? "+" : "-"}${Math.abs(equity.tradingPnlUsd).toLocaleString()}
              </div>
            </div>
            <div className="border border-border rounded-sm px-2.5 py-2">
              <div className="text-[10px] uppercase text-muted-foreground mb-0.5">Deposits</div>
              <div className="text-green-400/90">+${equity.depositsUsd.toLocaleString()}</div>
            </div>
            <div className="border border-border rounded-sm px-2.5 py-2">
              <div className="text-[10px] uppercase text-muted-foreground mb-0.5">Withdrawals</div>
              <div className="text-red-400/90">-${equity.withdrawalsUsd.toLocaleString()}</div>
            </div>
          </div>

          <div className="divide-y divide-border border border-border rounded-sm w-full">
            {adjustments.slice(0, 6).map((adjustment) => (
              <div key={adjustment.id} className="flex items-center justify-between gap-3 px-3 py-1.5 text-xs font-mono">
                <span className={adjustment.adjustmentType === "add" ? "text-green-400" : "text-red-400"}>
                  {adjustment.adjustmentType === "add" ? "+" : "-"}${adjustment.amountUsd.toFixed(2)}
                </span>
                <span className="text-muted-foreground flex-1 truncate">{adjustment.note || "Capital adjustment"}</span>
                <div className="flex items-center gap-2">
                  <span className="text-muted-foreground shrink-0">{new Date(adjustment.createdAt).toLocaleDateString()}</span>
                  <button
                    type="button"
                    className="text-muted-foreground hover:text-red-400 transition-colors p-1"
                    title="Delete adjustment"
                    onClick={() => deleteCapitalAdjustment(adjustment.id)}
                  >
                    <Trash2 size={13} />
                  </button>
                </div>
              </div>
            ))}
            {adjustments.length === 0 && (
              <div className="px-3 py-3 text-xs text-muted-foreground text-center">No capital adjustments yet.</div>
            )}
          </div>

          <button
            type="button"
            className="w-full py-2 text-sm font-mono font-medium bg-foreground text-background rounded-md hover:bg-foreground/90 transition-all active:scale-[0.98] flex items-center justify-center"
            onClick={handleSave}
          >
            {saved ? "Saved" : "Save Configuration"}
          </button>
        </div>
      </div>

      <div className="space-y-4">
        <div className="text-sm font-semibold px-1">Insight Sections</div>
        <p className="text-xs text-muted-foreground px-1 leading-relaxed max-w-2xl">
          The output screen summarizes similar historical trades and probability-based context from your own journal.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {DECISION_SCREEN.map(({ state, note }) => (
            <div key={state} className="p-4 border border-border/50 rounded-xl bg-card/10 flex flex-col gap-2 transition-colors hover:border-border/80">
              <span className="font-mono text-sm font-bold text-foreground tracking-tight">{state}</span>
              <span className="text-xs text-muted-foreground leading-relaxed">{note}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4 pt-4">
        <div className="text-sm font-semibold px-1">Similarity Pipeline</div>
        <div className="p-5 border border-border/50 rounded-xl bg-card/10 space-y-1">
          {PIPELINE_STEPS.map((step, idx) => (
            <div key={step} className="flex items-start gap-3 p-2 rounded-lg hover:bg-background/50 transition-colors">
              <div className="flex items-center justify-center w-5 h-5 rounded-full bg-muted/60 text-[10px] font-mono font-medium text-foreground/70 shrink-0 mt-0.5 border border-border/50">
                {idx + 1}
              </div>
              <span className="text-xs font-mono text-muted-foreground leading-relaxed pt-0.5">{step}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4 pt-4">
        <div className="text-sm font-semibold px-1">Similarity Buckets</div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {CLASSIFICATIONS.map(({ range, label, note }) => (
            <div key={range} className="flex flex-col sm:flex-row gap-3 p-4 rounded-xl border border-border/50 bg-card/10 transition-colors hover:border-border/80">
              <div className="font-mono text-sm font-bold text-muted-foreground shrink-0 w-16 mt-0.5">
                {range}
              </div>
              <div className="flex flex-col gap-1.5">
                <span className="text-sm font-bold text-foreground">{label}</span>
                <span className="text-xs text-muted-foreground leading-relaxed">{note}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4 pt-4">
        <div className="text-sm font-semibold px-1">Similarity Weights</div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {LAYERS.map(({ label, weight, note, icon: Icon }) => (
            <div key={label} className="p-4 border border-border/50 rounded-xl bg-card/10 flex flex-col gap-3 transition-colors hover:border-border/80">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <Icon className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-semibold text-foreground">{label}</span>
                </div>
                <span className="font-mono text-xs font-bold text-foreground">{weight}</span>
              </div>
              <span className="text-xs text-muted-foreground leading-relaxed">{note}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4 pt-4">
        <div className="text-sm font-semibold px-1">Model Notes</div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">
          {HARD_FILTERS.map(({ id, rule, result }) => (
            <div key={id} className="p-4 border border-border/50 rounded-xl bg-card/10 space-y-2">
              <div className="flex items-center justify-between gap-3">
                <span className="font-mono text-xs font-bold text-foreground">{id}</span>
                <span className="font-mono text-[10px] text-muted-foreground">{result}</span>
              </div>
              <div className="text-xs text-muted-foreground leading-relaxed">{rule}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4 pt-4">
        <div className="text-sm font-semibold px-1">Weighted Outcome</div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {ALLOCATION_RULES.map(({ label, value, note }) => (
            <div key={label} className="grid grid-cols-[140px_90px_1fr] gap-3 p-4 border border-border/50 rounded-xl bg-card/10 text-xs">
              <span className="font-semibold text-foreground">{label}</span>
              <span className="font-mono text-muted-foreground">{value}</span>
              <span className="text-muted-foreground leading-relaxed">{note}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="space-y-4 pt-4">
        <div className="text-sm font-semibold px-1">Reference Notes</div>
        <div className="p-5 border border-border/50 rounded-xl bg-card/10 space-y-1">
          {GUARDRAILS.map((note) => (
            <div key={note} className="flex items-start gap-3 p-2 rounded-lg hover:bg-background/50 transition-colors text-xs text-muted-foreground leading-relaxed">
              <div className="w-1.5 h-1.5 rounded-full bg-muted-foreground/30 shrink-0 mt-1.5" />
              <span className="pt-0.5">{note}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
